jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      # PASO NUEVO: Instalar pnpm en el servidor de GitHub
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Instala la versión más reciente de pnpm
          
      - name: Install, build, and upload your Astro site
        uses: withastro/action@v3
        with:
          # PASO NUEVO: Forzamos el gestor para evitar la auto-detección
          package-manager: pnpm 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4